version: '3'

services:
  postgres_producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zyfra-postgres-producer
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: producer
    ports:
      - "5433:5432"
    command: -c wal_level=logical -c max_replication_slots=5 -c max_wal_senders=5 -c wal_sender_timeout=20000
    volumes:
      - postgres_producer_data:/var/lib/postgresql/data
      - ./initdb_producer.sh:/docker-entrypoint-initdb.d/initdb.sh
    restart: always

  postgres_consumer:
    image: postgres:16
    container_name: zyfra-postgres-consumer
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: consumer
    ports:
      - "5432:5432"
    volumes:
      - postgres_consumer_data:/var/lib/postgresql/data
      - ./initdb_consumer.sh:/docker-entrypoint-initdb.d/initdb.sh
    restart: always


volumes:
  postgres_consumer_data:
  postgres_producer_data: